eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8764
spring:
  application:
    name: vice-zuul
zuul:
  routes:
    client-hi:
      path: /hhhi/**
      serviceId: service-hi
    consumer:
          path: /consu/**
          serviceId: vice-consumer

